### ISSUE TITLE
Profile form CSS hiding all initial removal buttons (not just for an entire property)

### ISSUE THREAD

**Issue by aploshay** [samvera-labs/allinson_flex#68]
The [style block injected into the profile form](https://github.com/samvera-labs/allinson_flex/blob/master/app/javascript/components/allinson_flex_profile_form.jsx#L179-L188) has some lines seemingly intended to block the add/remove buttons only at the level of an entire property, but have the side effect of also blocking the remove button for a single item in an array within the property form.

Suggest replacing:
```CSS
          button.btn-danger:nth-child(1) {
            display: none
          }
          #root > .row {
            display: none
          }
```

with:
```CSS
          /* hide removal button for entire property object */
          #root > div.form-group > div.row > div:nth-child(3) > button.btn-danger {
            display: none
          }

          /* hide add button for entire property object */
          #root > .row {
            display: none
          }
```
